version: "3.8"
services:
    db:
        image: mysql
        container_name: db
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - "6033:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mypass123
            MYSQL_DATABASE: commersive
            MYSQL_USER: admin
            MYSQL_PASSWORD: mypass123
        volumes:
            - ./db:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        links:
            - "db"
        restart: always
        ports:
            - "8081:80"
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
volumes:
    db:
        driver: local